import type { SearchableSelectOption } from '@/components/ui/searchable-select';

// Broad + common cattle breeds for marketplace filtering. Alphabetical by label, Other last.
export const CATTLE_BREED_OPTIONS: SearchableSelectOption[] = [
  { value: 'angus', label: 'Angus' },
  { value: 'ayrshire', label: 'Ayrshire' },
  { value: 'belgian_blue', label: 'Belgian Blue' },
  { value: 'black_angus', label: 'Black Angus' },
  { value: 'braford', label: 'Braford' },
  { value: 'brahman', label: 'Brahman' },
  { value: 'brahmousin', label: 'Brahmousin' },
  { value: 'brangus', label: 'Brangus' },
  { value: 'beefmaster', label: 'Beefmaster' },
  { value: 'brown_swiss', label: 'Brown Swiss' },
  { value: 'charolais', label: 'Charolais' },
  { value: 'chiangus', label: 'ChiAngus' },
  { value: 'chianina', label: 'Chianina' },
  { value: 'commercial_cross', label: 'Commercial / Crossbred' },
  { value: 'dexter', label: 'Dexter' },
  { value: 'gelbvieh', label: 'Gelbvieh' },
  { value: 'guernsey', label: 'Guernsey' },
  { value: 'hereford', label: 'Hereford' },
  { value: 'highland', label: 'Highland' },
  { value: 'holstein', label: 'Holstein' },
  { value: 'jersey', label: 'Jersey' },
  { value: 'limflex', label: 'Lim-Flex' },
  { value: 'limousin', label: 'Limousin' },
  { value: 'lowline_angus', label: 'Lowline Angus' },
  { value: 'maine_anjou', label: 'Maine-Anjou' },
  { value: 'murray_grey', label: 'Murray Grey' },
  { value: 'piedmontese', label: 'Piedmontese' },
  { value: 'polled_hereford', label: 'Polled Hereford' },
  { value: 'red_angus', label: 'Red Angus' },
  { value: 'salers', label: 'Salers' },
  { value: 'santa_gertrudis', label: 'Santa Gertrudis' },
  { value: 'senepol', label: 'Senepol' },
  { value: 'shorthorn', label: 'Shorthorn' },
  { value: 'simangus', label: 'SimAngus' },
  { value: 'simmental', label: 'Simmental' },
  { value: 'speckle_park', label: 'Speckle Park' },
  { value: 'longhorn', label: 'Texas Longhorn' },
  { value: 'wagyu', label: 'Wagyu' },
  { value: 'other', label: 'Other (not listed)' },
];

