import type { SearchableSelectOption } from '@/components/ui/searchable-select';

// "Sporting / working dogs" is broad; this list is intentionally large and filter-friendly.
// Users can choose "Other (not listed)" and enter free-text details as needed.
export const DOG_BREED_OPTIONS: SearchableSelectOption[] = [
  { value: 'labrador_retriever', label: 'Labrador Retriever' },
  { value: 'golden_retriever', label: 'Golden Retriever' },
  { value: 'german_shorthaired_pointer', label: 'German Shorthaired Pointer' },
  { value: 'german_wirehaired_pointer', label: 'German Wirehaired Pointer' },
  { value: 'wirehaired_pointing_griffon', label: 'Wirehaired Pointing Griffon' },
  { value: 'brittany', label: 'Brittany' },
  { value: 'english_setter', label: 'English Setter' },
  { value: 'gordon_setter', label: 'Gordon Setter' },
  { value: 'irish_setter', label: 'Irish Setter' },
  { value: 'weimaraner', label: 'Weimaraner' },
  { value: 'vizsla', label: 'Vizsla' },
  { value: 'spinone_italiano', label: 'Spinone Italiano' },
  { value: 'pointer', label: 'Pointer' },
  { value: 'chesapeake_bay_retriever', label: 'Chesapeake Bay Retriever' },
  { value: 'flat_coated_retriever', label: 'Flat-Coated Retriever' },
  { value: 'curly_coated_retriever', label: 'Curly-Coated Retriever' },
  { value: 'nova_scotia_duck_tolling_retriever', label: 'Nova Scotia Duck Tolling Retriever' },
  { value: 'english_springer_spaniel', label: 'English Springer Spaniel' },
  { value: 'welsh_springer_spaniel', label: 'Welsh Springer Spaniel' },
  { value: 'cocker_spaniel', label: 'Cocker Spaniel' },
  { value: 'english_cocker_spaniel', label: 'English Cocker Spaniel' },
  { value: 'boykin_spaniel', label: 'Boykin Spaniel' },
  { value: 'american_water_spaniel', label: 'American Water Spaniel' },
  { value: 'clumber_spaniel', label: 'Clumber Spaniel' },
  { value: 'field_spaniel', label: 'Field Spaniel' },
  { value: 'sussex_spaniel', label: 'Sussex Spaniel' },
  { value: 'irish_water_spaniel', label: 'Irish Water Spaniel' },
  { value: 'lagotto_romagnolo', label: 'Lagotto Romagnolo' },
  { value: 'pudelpointer', label: 'Pudelpointer' },
  { value: 'small_munsterlander', label: 'Small Münsterländer' },
  { value: 'large_munsterlander', label: 'Large Münsterländer' },
  { value: 'wirehaired_vizsla', label: 'Wirehaired Vizsla' },
  { value: 'english_pointer', label: 'English Pointer' },
  { value: 'english_foxhound', label: 'English Foxhound' },
  { value: 'treeing_walker_coonhound', label: 'Treeing Walker Coonhound' },
  { value: 'bluetick_coonhound', label: 'Bluetick Coonhound' },
  { value: 'black_and_tan_coonhound', label: 'Black and Tan Coonhound' },
  { value: 'redbone_coonhound', label: 'Redbone Coonhound' },
  { value: 'plott_hound', label: 'Plott Hound' },
  { value: 'american_foxhound', label: 'American Foxhound' },
  { value: 'beagle', label: 'Beagle' },
  { value: 'basset_hound', label: 'Basset Hound' },
  { value: 'bloodhound', label: 'Bloodhound' },
  { value: 'dachshund', label: 'Dachshund' },
  { value: 'rhodesian_ridgeback', label: 'Rhodesian Ridgeback' },
  { value: 'great_pyrenees', label: 'Great Pyrenees' },
  { value: 'anatolian_shepherd', label: 'Anatolian Shepherd Dog' },
  { value: 'kangal', label: 'Kangal (LGD)' },
  { value: 'maremma_sheepdog', label: 'Maremma Sheepdog' },
  { value: 'akbash', label: 'Akbash' },
  { value: 'komondor', label: 'Komondor' },
  { value: 'kuvasz', label: 'Kuvasz' },
  { value: 'border_collie', label: 'Border Collie' },
  { value: 'australian_shepherd', label: 'Australian Shepherd' },
  { value: 'australian_cattle_dog', label: 'Australian Cattle Dog' },
  { value: 'kelpie', label: 'Australian Kelpie' },
  { value: 'german_shepherd', label: 'German Shepherd Dog' },
  { value: 'belgian_malinois', label: 'Belgian Malinois' },
  { value: 'belgian_tervuren', label: 'Belgian Tervuren' },
  { value: 'belgian_sheepdog', label: 'Belgian Sheepdog' },
  { value: 'dutch_shepherd', label: 'Dutch Shepherd' },
  { value: 'rottweiler', label: 'Rottweiler' },
  { value: 'doberman_pinscher', label: 'Doberman Pinscher' },
  { value: 'boxer', label: 'Boxer' },
  { value: 'giant_schnauzer', label: 'Giant Schnauzer' },
  { value: 'standard_schnauzer', label: 'Standard Schnauzer' },
  { value: 'miniature_schnauzer', label: 'Miniature Schnauzer' },
  { value: 'pit_bull_type', label: 'Pit Bull-type (APBT/AmStaff/etc.)' },
  { value: 'american_staffordshire_terrier', label: 'American Staffordshire Terrier' },
  { value: 'american_pit_bull_terrier', label: 'American Pit Bull Terrier' },
  { value: 'cane_corso', label: 'Cane Corso' },
  { value: 'mastiff', label: 'Mastiff' },
  { value: 'bullmastiff', label: 'Bullmastiff' },
  { value: 'great_dane', label: 'Great Dane' },
  { value: 'other', label: 'Other (not listed)' },
  { value: 'mixed', label: 'Mixed / Crossbred' },
];

