import type { SearchableSelectOption } from '@/components/ui/searchable-select';

export const EQUIPMENT_MAKE_OPTIONS: SearchableSelectOption[] = [
  { value: 'john_deere', label: 'John Deere' },
  { value: 'kubota', label: 'Kubota' },
  { value: 'case_ih', label: 'Case IH' },
  { value: 'new_holland', label: 'New Holland' },
  { value: 'mahindra', label: 'Mahindra' },
  { value: 'massey_ferguson', label: 'Massey Ferguson' },
  { value: 'claas', label: 'CLAAS' },
  { value: 'fendt', label: 'Fendt' },
  { value: 'deutz_fahr', label: 'Deutz-Fahr' },
  { value: 'kioti', label: 'KIOTI' },
  { value: 'ls_tractor', label: 'LS Tractor' },
  { value: 'tym', label: 'TYM' },
  { value: 'bobcat', label: 'Bobcat' },
  { value: 'caterpillar', label: 'Caterpillar' },
  { value: 'komatsu', label: 'Komatsu' },
  { value: 'takeuchi', label: 'Takeuchi' },
  { value: 'jcb', label: 'JCB' },
  { value: 'gehl', label: 'Gehl' },
  { value: 'vermeer', label: 'Vermeer' },
  { value: 'hustler', label: 'Hustler' },
  { value: 'bush_hog', label: 'Bush Hog' },
  { value: 'land_pride', label: 'Land Pride' },
  { value: 'woods', label: 'Woods' },
  { value: 'rhino', label: 'Rhino' },
  { value: 'frontier', label: 'Frontier' },
  { value: 'dixie_chopper', label: 'Dixie Chopper' },
  { value: 'bad_boy', label: 'Bad Boy' },
  { value: 'scag', label: 'Scag' },
  { value: 'exmark', label: 'Exmark' },
  { value: 'gravely', label: 'Gravely' },
  { value: 'husqvarna', label: 'Husqvarna' },
  { value: 'stihl', label: 'STIHL' },
  { value: 'toro', label: 'Toro' },
  { value: 'other', label: 'Other (not listed)' },
];

